### ISSUE TITLE
build database

### ISSUE THREAD

**Issue by dspape** [Pinqua/Radon#1]
Hi Piyush,
I found your platform superb, suddenly I wanted to climb locally but I have a problem with the database, can you please explain to me how to prepare the necessary data.

![Error](https://user-images.githubusercontent.com/107435170/173813118-5481340f-a2a6-4346-a48d-8dd68b434d75.png)

**Comment by Pinqua** [comment]
You need to create a MongoDB database (https://account.mongodb.com/account/login) and then add the connection URL and database name in the .env.local(check .env.local.example file --- you can rename it to .env.local to use locally and add require info in that  ) file 

Use MongoDB connection URL with driver node.js and version 2.2.12 or later
MONGODB_URI= add connection URL here in the .env.local file
Your database name
MONGODB_DB=add database name here in the .env.local file
